# Generated by Django 2.0.4 on 2018-05-08 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180429_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='geolocation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
